---
- hosts: localhost
  connection: local
  remote_user: Administrator

  vars_files:
    - Vars/var.yml
    - Vars/aws.yml

  vars_prompt:
    - name: "frequency"
      prompt: "Please enter the frequency of reating the snapshot: Ex: Daily, Weekly, Monthly"
      private: no

  tasks:
    - name: Automating EBS Volume Snapshot on AWS | Find EC2 Instances with Snapshot Tag
      ec2_remote_facts:
        aws_access_key: "{{ AWS_ACCESS_KEY }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        region: "{{ SNAPSHOT_SOURCE }}"
        filters:
          "tag:Snapshot": "Yes"
      register: ec2_nets

    - name: Automating EBS Volume Snapshot on AWS | Print out EC2 Instance ID 
      debug:
        var: ec2_nets.instances[0].id

    - name: Automating EBS Volume Snapshot on AWS | Set Instance ID in a Variable
      set_fact:
        instanceid: "{{ ec2_nets.instances[0].id }}"

    - name: Automating EBS Volume Snapshot on AWS | Print out the Device Name
      debug:
        var: ec2_nets.instances[0].block_device_mapping[0].device_name

    - name: Automating EBS Volume Snapshot on AWS | Set Device Name in a Variable
      set_fact:
        devicename: "{{ ec2_nets.instances[0].block_device_mapping[0].device_name }}"

    - name: Automating EBS Volume Snapshot on AWS | Print out Instance Name 
      debug:
        var: ec2_nets.instances[0].tags.Name

    - name: Automating EBS Volume Snapshot on AWS | Set Instance Name in a Variable
      set_fact:
        instancename: "{{ ec2_nets.instances[0].tags.Name }}"

    - name: Automating EBS Volume Snapshot on AWS | Print out Volume ID 
      debug:
        var: ec2_nets.instances[0].block_device_mapping[0].volume_id

    - name: Automating EBS Volume Snapshot on AWS | Set Volume ID in a Variable
      set_fact:
        volumeid: "{{ ec2_nets.instances[0].block_device_mapping[0].volume_id }}"

    - name: Automating EBS Volume Snapshot on AWS | Create EBS Snapshot
      ec2_snapshot:
        aws_access_key: "{{ AWS_ACCESS_KEY }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        region: "{{ SNAPSHOT_SOURCE }}"
        instance_id: "{{ instanceid }}"
        device_name: "{{ devicename }}"
        description: "This snapshot is taken on {{ ansible_date_time.date }} at {{ ansible_date_time.time }}"
        snapshot_tags:
          Name: "{{ instancename }}_{{ ansible_date_time.date }}"
          Instance: "{{ instancename }}"
      register: snapshot_info

    - name: Automating EBS Volume Snapshot on AWS | Set Snapshot ID in a Variable
      set_fact: 
        snapid: "{{ snapshot_info.snapshot_id }}"
        
    - name: Automating EBS Volume Snapshot on AWS | Copy the Snapshot to the DR Region
      ec2_snapshot_copy:
        aws_access_key: "{{ AWS_ACCESS_KEY }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        description: "This snapshot is taken on {{ ansible_date_time.date }} at {{ ansible_date_time.time }}"
        region: "{{ SNAPSHOT_REGION }}"
        source_region: "{{ SNAPSHOT_SOURCE }}"
        source_snapshot_id: "{{ snapid }}"
        tags:
          Name: "{{ instancename }}_{{ ansible_date_time.date }}"
          Instance: "{{ instancename }}"
          Volume_ID: "{{ volumeid }}"
      register: snap2

    - name: Automating EBS Volume Snapshot on AWS | Print out Snapshot Info
      debug:
        var: snap2
